Refactor: 식사시간 초단위 주기 추가
BCSDLab/KOIN_BATCH pull request #59
Opened 2024-03-25 08:40 UTC by ImTotem

- close #58 

학생식당(학생회관 2층) 기준으로 10초마다 크롤링하도록 추가하였습니다.
- 조식 08:00~09:30
- 중식 11:30~13:30
- 석식 17:30~18:30

2024-03-25 08:50 UTC, Choi-JJunho approved these changes
굿~!
간단한 코멘트 남겼으니 확인 부탁드려용~

2024-03-25 08:50 UTC, Choi-JJunho commented on README.md
> +pip3 install -r requirements.txt
### A
오~! requirements.txt 좋아요~

2024-03-25 08:50 UTC, Choi-JJunho commented on crawling/koreatech_dining.py
> +        print(f"waiting {sleep} seconds...")
### C

로그 파악하기 용이하도록 텍스트를 구성해보는건 어떨까요?
ex) `조식 업데이트중...` / `중식 업데이트중...` / `석식 업데이트중...`

2024-03-25 08:52 UTC, Choi-JJunho requested changes
깜빡한 내용이 생각나서 다시 RC 드려봅니다

2024-03-25 08:52 UTC, Choi-JJunho commented on crawling/koreatech_dining.py
> +        crawling()
### R
앗 이거 잠시 깜빡했네요
crawling을 수행했을 때 기존값과 같으면 update를 수행하지 않으면 좋겠어요~~
DB insert 작업을 최소화시켜보죠~!

2024-03-25 09:19 UTC, Invidam commented on crawling/koreatech_dining.py
> +        crawling()
## C
저도 같은 생각입니다~ 
실시간인 경우에는 기존과 달리 더욱 효율적인 프로그램일 필요가 있을 것 같아요!

기존값과 같은지 비교하기 위한 방법들(중복 검사 알고리즘)도 많을 것 같아요

2024-03-25 10:13 UTC, johnny19991006 commented on crawling/koreatech_dining.py
> +        crawling()
10씩이면 db메모리 터질수도 있겠네요 저때 (micro서버에 sql두개가 저러면)

2024-03-26 02:28 UTC, ImTotem commented on crawling/koreatech_dining.py
> +        print(f"waiting {sleep} seconds...")
수정했습니다~ 👍

2024-03-26 02:28 UTC, ImTotem commented on crawling/koreatech_dining.py
> +        crawling()
수정했습니다~ 👍

2024-03-26 03:25 UTC, songsunkook requested changes
파이썬 어렵네요... 👍
코드에 대한 피드백은 힘들지만 로직 관련해서 궁금한 점 코멘트 남겨드렸습니다. 확인부탁드려요!

2024-03-26 03:25 UTC, songsunkook commented on crawling/koreatech_dining.py
> +        today_menus = menus
### R

Q1) 식사시간 여부에 따라 작업 제한을 두는 건 DB 업데이트에 한정되는 건가요?
    - 크롤링은 식사시간 상관없이 10초마다 수행하나요? 만약 그렇다면 비효율적일 것 같습니다.

Q2) 식사시간이 아닌 때 메뉴가 변경되면 반영이 안되나요? 
    - 큰 문제가 없긴 한데, 별도의 cron으로 돌리는 것인지.. 잘 모르겠습니다

2024-03-26 03:25 UTC, songsunkook commented on crawling/koreatech_dining.py
>      connection = connect_db()
### R
가능할지 모르겠지만 식단 정보를 레디스에 저장하는 방향은 어떻게 생각하시나요?
근거는 아래와 같습니다. (파이썬이 낯설어서 틀린 내용이 있을 수 있습니다)

1. 10초마다 크롤링 결과와 DB 내용을 비교하기 위해 mySQL에 select 요청을 한다.
2. WAS에서는 메뉴 변경 여부를 파악하기 위해 10초마다 mySQL에 select 요청을 하여 비교한다.

로직을 아래와 같이 수정한다면 자주 일어날 mySQL 요청을 Redis 요청으로 바꾸어 I/O 속도가 서버 부하에 긍정적 영향이 있을 것이라고 생각합니다. 

(식사시간 한정)
1. koreatech_dining.py는 크롤링 결과를 Redis에 저장한다.
2. WAS는 Redis를 조회하여 메뉴 변경 여부를 파악한다.
3. WAS는 메뉴가 변경된 경우 변경된 내용을 mySQL에 반영한다.

오버엔지니어링이라고 판단되면 굳이 바꾸지 않아도 됩니다.
내용 중 틀린 내용이 있으면 말씀해주세요!

2024-03-26 03:45 UTC, ImTotem commented on crawling/koreatech_dining.py
> +        today_menus = menus
A1)
식사시간동안에만 10초마다 수행을 합니다.
```python3
while meal_time := check_meal_time():
    ...
```
식사시간에 해당하는 식단 정보인지 판단하기 위하여 식단의 시간은 10초마다 파싱하게 됩니다.
해당하는 식사시간이 아니라면 건너뛰도록 되어있습니다.

A2)
원래 cron으로 [**매일 05시 00분, 09시 00분, 15시 00분**](https://docs.google.com/document/d/1-kHjeV6py-Qa9LGy6nBjwnRS-Bzz9jMJ0fAUCrUpMgc/edit)에 수행하도록 되어있습니다.
**매일 05시 00분 / 08시 00분 / 11시 30분 / 15시 00분 / 17시 30분**에 실행되도록 cron을 수정할 예정입니다.
이렇게 수정하면 너무 많이 실행된다고 느껴지기는 하네요..

2024-03-26 03:52 UTC, Choi-JJunho commented on crawling/koreatech_dining.py
>      connection = connect_db()
이렇게되면 WAS에서 Redis를 계속 감시해야하는건가요?

2024-03-26 03:58 UTC, Choi-JJunho approved these changes
고생하셨습니다 👍

2024-03-26 03:58 UTC, Choi-JJunho commented on crawling/koreatech_dining.py
> +    menu_a = {(menu.date, menu.dining_time, menu.place): menu for menu in menu_a}
### R
음 변수명이 알고리즘같군요 ㅋㅋㅋㅋㅋㅋ
나중에 다른 사람이 알아보기 조금은 편하게 만들어보는건 어떨까요

```suggestion
def check_duplication_menu(existed_menu: list[MenuEntity | None], new_menu: list[MenuEntity | None]):
    existed_menu = {(menu.date, menu.dining_time, menu.place): menu for menu in existed_menu}
```

2024-03-26 04:03 UTC, ImTotem commented on crawling/koreatech_dining.py
>      connection = connect_db()
> 1. 10초마다 크롤링 결과와 DB 내용을 비교하기 위해 mySQL에 select 요청을 한다.

10초마다 크롤링 결과를 비교할때 mySQL에 select하지 않고있습니다.
- select 요청을 하는 것도 서버 부하가 생길 것 같아서 today_menus 변수에 저장하여 비교하고 있습니다.
```python3
def loop_crawling(sleep=10):
    crawling()
    today_menus = getMenus(target_date=datetime.datetime.now(), target_time=check_meal_time())
    while ...
```
> 2. WAS에서는 메뉴 변경 여부를 파악하기 위해 10초마다 mySQL에 select 요청을 하여 비교한다.

koreatech_dining.py에서 WAS로 메뉴 변경이 발생했다는 정보를 다이렉트로 알려줄 수 있는 방법을 찾아보면 좋을 것 같아요.
(설마 없나...?)

2024-03-26 04:05 UTC, ImTotem commented on crawling/koreatech_dining.py
> +    menu_a = {(menu.date, menu.dining_time, menu.place): menu for menu in menu_a}
수정했습니다 ㅋㅋㅋㅋㅋ

2024-03-26 04:32 UTC, songsunkook commented on crawling/koreatech_dining.py
>      connection = connect_db()
매번 select를 안하고 있다면 크게 바꿔야 할 것 같지는 않네요!

> koreatech_dining.py에서 WAS로 메뉴 변경이 발생했다는 정보를 다이렉트로 알려줄 수 있는 방법을 찾아보면 좋을 것 같아요.
(설마 없나...?)

현재로써는 레디스에 저장하고 WAS에서 존재여부 확인 정도밖에 떠오르지 않네요

2024-03-26 04:32 UTC, songsunkook approved these changes
고생하셨습니다! 파이썬고수 ㄷㄷ

2024-03-26 06:15 UTC, merged