Refactor: is_changed 추가
BCSDLab/KOIN_BATCH pull request #65
Opened 2024-03-28 04:37 UTC by ImTotem

- close #64 

sql에 `is_changed`를 추가했습니다.

10초마다 크롤링 할때 메뉴가 변경되면 `is_changed`가 `True`로 업데이트됩니다.

2024-03-28 04:45 UTC, Choi-JJunho requested changes
이게 왜 추가되었나요?

+) target 브랜치 develop으로 바꿔주세용

2024-03-28 04:45 UTC, Choi-JJunho commented on crawling/koreatech_dining.py
> +            INSERT INTO koin.dining_menus(date, type, place, price_card, price_cash, kcal, menu, is_changed)
### R

DB에 is_changed라는 컬럼이 없는데요?
<img width="433" alt="image" src="https://github.com/BCSDLab/KOIN_BATCH/assets/49794401/df541ef7-e14c-49d9-8d9a-2f742f752393">

이거 추가하게된 이유가 뭔가요
영양사님은 메뉴를 여러번 수정하실 수도 있는데 이게 어떤면에서 효과를 볼 수 있는거죠?

2024-03-28 04:59 UTC, ImTotem commented on crawling/koreatech_dining.py
> +            INSERT INTO koin.dining_menus(date, type, place, price_card, price_cash, kcal, menu, is_changed)
KOIN_API_V2 Dining 엔티티에 레거시에 없던 `soldOut`과 `imageUrl`이 추가된것을 확인했습니다.
<img width="880" alt="image" src="https://github.com/BCSDLab/KOIN_BATCH/assets/46699595/d97dd767-09c5-4d88-8829-c192fa5579f3">
`is_changed`는 곧 코마 Dining에서 작성하여 PR할 예정입니다.

원래는 `created_at`과 `updated_at`을 비교해서 다르면 메뉴가 변경되었다고 판단할 생각이었습니다.

이렇게 비교하면 식사시간 이전에 메뉴가 변경되면 품절로 인한 변경인지 알 수 없는 문제가 발생할 수 있었습니다.
그래서 '식사 시간에 메뉴가 변경되었는가?'를 판단하기 위해 추가했습니다.

2024-03-28 05:04 UTC, Choi-JJunho commented on crawling/koreatech_dining.py
> +            INSERT INTO koin.dining_menus(date, type, place, price_card, price_cash, kcal, menu, is_changed)
메뉴가 변경되었음을 판단해야할 상황이 있나용?

+) 코마 Dining PR이 Merge되고 컬럼 생성된거 확인하고 어프로브할게요

2024-03-28 05:05 UTC, ImTotem commented on crawling/koreatech_dining.py
> +            INSERT INTO koin.dining_menus(date, type, place, price_card, price_cash, kcal, menu, is_changed)
메뉴가 변경되면 메뉴 사진위에 '품절됨'처럼 '변경됨'을 표시해주기 위해 필요하다고 했습니다

2024-03-28 05:06 UTC, Choi-JJunho commented on crawling/koreatech_dining.py
> +            INSERT INTO koin.dining_menus(date, type, place, price_card, price_cash, kcal, menu, is_changed)
오 그런 히스토리가 있었군요
좋습니다~👍
코마에 flyway 파일 머지되는거 확인하고 본 PR 다시 확인하겠습니다

2024-04-01 05:35 UTC, Choi-JJunho approved these changes
- https://github.com/BCSDLab/KOIN_API_V2/pull/250
해당 PR 머지해서 이친구도 같이 merge하겠습니다~

2024-04-01 05:35 UTC, merged