feat : 천원의 아침 카드 url 삽입 기능 추가
BCSDLab/KOIN_BATCH pull request #87
Opened 2024-06-07 13:40 UTC by Choon0414

메뉴에 '천원의아침' 문구가 포함되어있으면 천원의 아침 이미지 url을 함께 삽입하도록 추가하였습니다.

2024-06-08 07:51 UTC, songsunkook requested changes
식단 크롤링을 만지다가 느꼈던 신경쓰이는 부분이 있어서 코멘트남깁니다. 급하게 진행했으면 한다고 올렸었는데 RC걸어서 죄송합니당.. ㅠㅠ

2024-06-08 07:51 UTC, songsunkook commented on crawling/koreatech_portal/dining.py
>                  ON DUPLICATE KEY UPDATE price_card = %s, price_cash = %s, kcal = %s, menu = '%s', is_changed = %s
## R

**필요한 배경 지식**
- 이 쿼리는 중복되는 데이터(로우)가 있다면 쿼리에서 명시한 컬럼들에 대해서만 기존 값에 덮어씌우는 형식으로 동작합니다. 
- 이 쿼리는 기존과 메뉴 정보 등이 달라질 때 또는 코드 최초 실행 시(하루 약 4회) 동작합니다.

**우려되는 문제 상황**
- 앞서 언급했듯이 이 쿼리가 실행될 경우 **쿼리에서 명시된 컬럼 값**들이 덮어씌워지면서 사라집니다.
- PR 상으로는 여기서 image_url까지 명시가 되도록 바뀌었습니다.
- 특정 조건에 의해 이 쿼리가 실행될 때, 천원의 아침이 아니고 사진이 올라가있다면 해당 이미지 정보가 사라질 수 있을 것 같습니다. (덮어씌워지면서 NULL 기입)

**생각되는 해결 방안**
- INSERT 쿼리 호출 전에 SELECT 쿼리를 우선 호출하여 기존 값을 불러온다.
    - 쿼리 호출량이 늘어나 성능이 떨어집니다. (가능하다면 피하는 것이 좋다고 생각했습니다.)
- DB에는 image_url을 NULL로 유지하고 자바 코드 단에서 GET /dining 호출 시 직접 판단 후 DTO에 기입하는 방법이 생각납니다.

이 문제에 대해 어떻게 생각하시는지 궁금합니다! 제가 미처 생각하지 못한 다른 방안이 있다면 알려주시면 좋을 것 같아요.

2024-06-09 07:11 UTC, Choon0414 commented on crawling/koreatech_portal/dining.py
>                  ON DUPLICATE KEY UPDATE price_card = %s, price_cash = %s, kcal = %s, menu = '%s', is_changed = %s
제가 이해했던 바로는 
- 최초 삽입: image_url을 포함한 row 전체가 삽입됨
- 이후 크롤링 시: 중복된 row에 대해서는 ON DUPLICATE 부분에 있는 price_card, price_cash, kcal, menu, is_changed만 수정됨 
=> image_url은 최초 1회 새로운 삽입에 대해서만 url이 추가됨
을 생각하고 작성했었습니다! 혹시 코드가 설명과 다른가요?

만약 이 방법이 어렵다면  말씀하신 것처럼 크롤링 할 때보다 자바 코드 단에서 기존의 image_url이 null이 아닌지를 판단하는 과정을 처리하는 것이 더 효율적일 것 같습니다!

2024-06-09 07:16 UTC, songsunkook commented on crawling/koreatech_portal/dining.py
>                  ON DUPLICATE KEY UPDATE price_card = %s, price_cash = %s, kcal = %s, menu = '%s', is_changed = %s
그러네요! 말씀해주신 내용이 맞는 것 같습니다. 제가 헷갈렸네요. 감사합니다. 이대로 적용해도 좋을 것 같아요!

2024-06-09 07:17 UTC, songsunkook approved these changes
덕분에 하나 더 알아갑니다. 고생하셨습니다!

2024-06-09 07:18 UTC, merged