refactor: 아우누리 2차 인증 무시
BCSDLab/KOIN_BATCH pull request #93
Opened 2024-06-20 13:00 UTC by ImTotem

[대학 웹서비스(아우누리, 웹메일) 2차인증 적용 관련 안내](https://www.koreatech.ac.kr/notice/view.es?mid=a10604010000&board_id=14&post_seq=31809&prefix_id=0) 공지를 보면 교내 ip의 경우 2차인증이 필요 없음을 알 수 있습니다.

학교의 'KOREATECH' 와이파이에 접속하여 ip를 확인해보면 
<img width="1243" alt="image" src="https://github.com/BCSDLab/KOIN_BATCH/assets/46699595/81d3653f-3914-49ef-b1ef-9213252b7b77">
'Korea University of Technology and Education' 제공으로 뜨게 됩니다.
따라서 `X-Forwarded-For`, `X-Real-IP` 헤더를 추가하여 Client IP를 `203.255.221.XXX`인것처럼 속여주면 2차 인증 없이 로그인 할 수 있게 됩니다.

-----------------

- request들을 인터셉트하여 `X-Forwarded-For`, `X-Real-IP` 헤더를 추가해주도록 수정하였습니다.
- 막힐 경우를 생각하여 기존 2차인증 코드는 삭제하지 않았습니다.

-----------------

참고자료:
- https://umbum.dev/1221/
- https://github.com/AdguardTeam/StealthMode/blob/master/Extension/lib/stealth.js#L145
- https://stackoverflow.com/a/51919307
- 친구 제보:
<img width="200" alt="image" src="https://github.com/BCSDLab/KOIN_BATCH/assets/46699595/ad0e21c8-57f2-444a-9511-e636e28aeb54">

2024-06-21 06:09 UTC, songsunkook requested changes
어디서 이런 걸 찾아오시는 건지.. 신기하네요
몇 가지 질문드립니당

2024-06-21 06:09 UTC, songsunkook commented on requirements.txt
> +blinker==1.7.0
seleniumwire를 selenium 대신 사용하는 것 같은데 selenium은 남겨둔 이유가 있을까요?

2024-06-21 06:09 UTC, songsunkook commented on crawling/koreatech_portal/login.py
> +        print(e)
👍

2024-06-21 06:09 UTC, songsunkook commented on crawling/koreatech_portal/login.py
> +from seleniumwire import webdriver
참고자료로 올려주신 스택오버플로우를 보면 seleniumwire는 더이상 관리되지 않는 라이브러리라고 하는 것 같은데, 이걸 사용해도 괜찮은 건가요??

2024-06-22 12:17 UTC, ImTotem commented on requirements.txt
> +blinker==1.7.0
GPT의 도움으로 Chrome DevTools Protocol(CDP)로 수정했습니다 (이게 뭔지는 저도 모르겠어요)
따라서 selenium으로 롤백되었습니당

2024-07-01 04:36 UTC, songsunkook approved these changes

2024-07-01 04:54 UTC, merged